version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - docker.env
    networks:
      - postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    command: yarn run start:dev
    env_file:
      - .env
    networks:
      - postgres
    depends_on:
      - postgres

  # pgadmin:
  #   links:
  #     - postgres:postgres
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - '8080:80'
  #   env_file:
  #     - docker.env
  #   networks:
  #     - postgres

networks:
  postgres:
    driver: bridge
volumes:
  pgdata:
