FROM node:12.14-alpine As development

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn --only=development

COPY . .

RUN yarn run build

FROM node:12.14-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install --only=production

COPY . .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]